export enum Skill {
  C = 'C',
  Java = 'Java',
  JavaScript = 'JavaScript',
  TypeScript = 'TypeScript',
  Python = 'Python',
  Ruby = 'Ruby',
  Go = 'Go',
  Erlang = 'Erlang',
  PHP = 'PHP',
  HTML = 'HTML',
  CSS = 'CSS',
  SASS = 'SASS',
  Less = 'Less',
  SQL = 'SQL',
  MongoDB = 'MongoDB',
  Docker = 'Docker',
  Bootstrap = 'Bootstrap',
  C_PLUS = 'C++',
  C_Sharp = 'C#',
  Git = 'Git',
  TFS = 'TFS',
  UNSPECIFIED = '',
}
