export enum WorkType {
  OFFICE_FULL_TIME = 'FULL_TIME',
  REMOTELY_FULL_TIME = 'REMOTELY_FULL_TIME',
  REMOTELY_PART_TIME = 'REMOTELY_PART_TIME',
  FREELANCE = 'FREELANCE',
  PROJECT_BASED = 'PROJECT_BASED',
  OTHER = 'OTHER',
}
